VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "BankInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public BankID As Long
Public BankName As String
Public Country As String
Public Phone1 As String
Public Phone2 As String
Public Fax1 As String
Public Fax2 As String
Public Email1 As String
Public Email2 As String
Public Address1 As String
Public Address2 As String
Public DefaultBank As Boolean
